In [58]:
import urllib3
import requests
import pandas as pd
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

## Comune Milano

In [4]:
# save the URL string (without the limit=5 parameter) to a "url" object
url = 'https://dati.comune.milano.it/api/3/action/datastore_search?resource_id=dbd7417a-41e8-4097-a1c4-67094983bab1&limit=1000'

In [8]:
#usiamo libreria request e il metodo get
r = requests.get(url, verify=False)

In [9]:
r.status_code

200

In [27]:
df = pd.DataFrame.from_dict(r.json()['result']['records'])
df

     _id  Anno                 Data     Giorno  Totale (Smc)
0      1  2019  2019-01-01T00:00:00    Martedi     6603230.0
1      2  2019  2019-01-02T00:00:00  Mercoledi     6579016.0
2      3  2019  2019-01-03T00:00:00    Giovedi     7115704.0
3      4  2019  2019-01-04T00:00:00    Venerdi     7650062.0
4      5  2019  2019-01-05T00:00:00     Sabato     7471068.0
..   ...   ...                  ...        ...           ...
726  727  2020  2020-12-27T00:00:00   Domenica     6714208.0
727  728  2020  2020-12-28T00:00:00     Lunedi     7667257.0
728  729  2020  2020-12-29T00:00:00    Martedi     7897478.0
729  730  2020  2020-12-30T00:00:00  Mercoledi     7719484.0
730  731  2020  2020-12-31T00:00:00    Giovedi     7773887.0

[731 rows x 5 columns]

## Binance

In [16]:
url_binance = 'https://api2.binance.com/api/v3/ticker/24hr'
bnc = requests.get(url_binance)

In [ ]:
bnc.json()[0:3]
#molto semplice, è una lista[], ogni elemento della lista è un dizionario{}, ogni elemento del dizionario chaive-valore è colonna e valore.

[{'symbol': 'ETHBTC',
  'priceChange': '-0.00002000',
  'priceChangePercent': '-0.062',
  'weightedAvgPrice': '0.03206317',
  'prevClosePrice': '0.03214000',
  'lastPrice': '0.03211000',
  'lastQty': '0.01610000',
  'bidPrice': '0.03210000',
  'bidQty': '81.34800000',
  'askPrice': '0.03211000',
  'askQty': '0.00040000',
  'openPrice': '0.03213000',
  'highPrice': '0.03230000',
  'lowPrice': '0.03185000',
  'volume': '6884.70510000',
  'quoteVolume': '220.74545957',
  'openTime': 1790763491499,
  'closeTime': 1790849891499,
  'firstId': 533068101,
  'lastId': 533087475,
  'count': 19375},
 {'symbol': 'LTCBTC',
  'priceChange': '-0.00000400',
  'priceChangePercent': '-0.498',
  'weightedAvgPrice': '0.00079868',
  'prevClosePrice': '0.00080200',
  'lastPrice': '0.00079900',
  'lastQty': '8.53300000',
  'bidPrice': '0.00080000',
  'bidQty': '37.63300000',
  'askPrice': '0.00080100',
  'askQty': '67.51700000',
  'openPrice': '0.00080300',
  'highPrice': '0.00080900',
  'lowPrice': '0.00078300',
  'volume': '9245.35800000',
  'quoteVolume': '7.38405964',
  'openTime': 1790763492960,
  'closeTime': 1790849892960,
  'firstId': 107351069,
  'lastId': 107353311,
  'count': 2243},
 {'symbol': 'BNBBTC',
  'priceChange': '0.00001600',
  'priceChangePercent': '0.175',
  'weightedAvgPrice': '0.00916570',
  'prevClosePrice': '0.00916400',
  'lastPrice': '0.00917900',
  'lastQty': '0.01600000',
  'bidPrice': '0.00917900',
  'bidQty': '9.20200000',
  'askPrice': '0.00918100',
  'askQty': '5.97100000',
  'openPrice': '0.00916300',
  'highPrice': '0.00922500',
  'lowPrice': '0.00907800',
  'volume': '5458.21500000',
  'quoteVolume': '50.02837920',
  'openTime': 1790763493099,
  'closeTime': 1790849893099,
  'firstId': 288445537,
  'lastId': 288459812,
  'count': 14276}]

In [ ]:
dfBinance = pd.DataFrame.from_dict(bnc.json()) #gli diciamo 'fai un datFRAME, ogni riga è un dizionario'
dfBinance

,symbol,priceChange,priceChangePercent,weightedAvgPrice,prevClosePrice,lastPrice,lastQty,bidPrice,bidQty,askPrice,...,openPrice,highPrice,lowPrice,volume,quoteVolume,openTime,closeTime,firstId,lastId,count
0,ETHBTC,-0.00002000,-0.062,0.03206317,0.03214000,0.03211000,0.01610000,0.03210000,81.34800000,0.03211000,...,0.03213000,0.03230000,0.03185000,6884.70510000,220.74545957,1790763491499,1790849891499,533068101,533087475,19375
1,LTCBTC,-0.00000400,-0.498,0.00079868,0.00080200,0.00079900,8.53300000,0.00080000,37.63300000,0.00080100,...,0.00080300,0.00080900,0.00078300,9245.35800000,7.38405964,1790763492960,1790849892960,107351069,107353311,2243
2,BNBBTC,0.00001600,0.175,0.00916570,0.00916400,0.00917900,0.01600000,0.00917900,9.20200000,0.00918100,...,0.00916300,0.00922500,0.00907800,5458.21500000,50.02837920,1790763493099,1790849893099,288445537,288459812,14276
3,NEOBTC,-0.00000708,-16.659,0.00003993,0.00000000,0.00003542,18.03000000,0.00000000,0.00000000,0.00000000,...,0.00004250,0.00004353,0.00003542,241411.18000000,9.63985417,1788846735998,1788933135998,47803347,47807346,4000
4,QTUMETH,-0.00005160,-9.979,0.00046193,0.00000000,0.00046550,4.40000000,0.00000000,0.00000000,0.00000000,...,0.00051710,0.00070000,0.00039840,354110.50000000,163.57504584,1788846735998,1788933135998,5539691,5543690,4000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3718,HPEBUSDT,3.57000000,5.806,65.23486304,0.00000000,65.06000000,1.54000000,65.06000000,1.38000000,65.22000000,...,61.49000000,67.04000000,61.49000000,5047.81000000,329293.19400000,1790763269404,1790849669404,0,3519,3520
3719,PDDBUSDT,0.65000000,0.839,78.00317393,0.00000000,78.15000000,10.16000000,78.00000000,111.58000000,78.14000000,...,77.50000000,78.42000000,77.23000000,14722.20000000,1148378.32720000,1790762901561,1790849301561,0,4637,4638
3720,SHAZBUSDT,1.34000000,2.474,54.38879523,0.00000000,55.51000000,0.51000000,55.40000000,0.36000000,55.51000000,...,54.17000000,55.95000000,53.00000000,2554.84000000,138954.66960000,1790763404276,1790849804276,0,1393,1394
3721,WENBUSDT,-0.16000000,-2.446,6.55030182,0.00000000,6.38000000,2.60000000,6.36000000,1.90000000,6.38000000,...,6.54000000,6.76000000,6.34000000,30610.90000000,200510.63400000,1790763473295,1790849873295,0,2817,2818
3722,ZMBUSDT,2.47000000,2.795,90.47482028,0.00000000,90.83000000,0.14000000,90.67000000,0.27000000,90.83000000,...,88.36000000,92.15000000,88.36000000,1585.53000000,143450.54180000,1790763488996,1790849888996,0,1847,1848

## Bitcoin - prezzo ultimo anno

In [39]:
url = 'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart'
#ogni API ha documentato i parametri di cui ha bisogno
params = {
    'vs_currency': 'usd',
    'days': '365',
    'interval': 'daily'
}

In [40]:
response = requests.get(url, params=params)
data = response.json()
data
#la risposta è una lista di liste di valori

{'prices': [[1759536000000, 122294.92441742844],
  [1759622400000, 122428.89063350527],
  [1759708800000, 123488.7305970136],
  [1759795200000, 124739.81088811433],
  [1759881600000, 121463.11808164183],
  [1759968000000, 123342.98469750278],
  [1760054400000, 121718.66757741552],
  [1760140800000, 113043.67586321976],
  [1760227200000, 110655.26975977032],
  [1760313600000, 115060.88417839336],
  [1760400000000, 115226.58429002496],
  [1760486400000, 113066.35078450407],
  [1760572800000, 110844.40417180728],
  [1760659200000, 108168.17353436728],
  [1760745600000, 106483.89143637568],
  [1760832000000, 107210.0961099579],
  [1760918400000, 108655.50525004532],
  [1761004800000, 110535.86301373685],
  [1761091200000, 108301.75462476298],
  [1761177600000, 107591.4605093986],
  [1761264000000, 110109.30522515893],
  [1761350400000, 111030.1833786475],
  [1761436800000, 111631.63726547628],
  [1761523200000, 114419.22169689646],
  [1761609600000, 114085.33123756813],
  [1761696000000, 112893.85203624627],
  [1761782400000, 110026.087620204],
  [1761868800000, 108409.379924928],
  [1761955200000, 109566.6066188076],
  [1762041600000, 110066.94174051796],
  [1762128000000, 110499.52238345638],
  [1762214400000, 106451.70653262926],
  [1762300800000, 101480.76659609628],
  [1762387200000, 103878.9335997028],
  [1762473600000, 101261.6455104612],
  [1762560000000, 103191.7560668328],
  [1762646400000, 102286.82524827348],
  [1762732800000, 104610.22853607994],
  [1762819200000, 105951.49599987874],
  [1762905600000, 103112.21006199118],
  [1762992000000, 101633.69431605682],
  [1763078400000, 99480.3070908126],
  [1763164800000, 94772.61435799382],
  [1763251200000, 95380.13316661112],
  [1763337600000, 94188.27668924726],
  [1763424000000, 92100.36452360668],
  [1763510400000, 92903.18008511196],
  [1763596800000, 91408.3573343969],
  [1763683200000, 86618.47155915352],
  [1763769600000, 85087.95256265256],
  [1763856000000, 84675.50764856212],
  [1763942400000, 86740.11773876166],
  [1764028800000, 88256.04395603726],
  [1764115200000, 87317.00455056976],
  [1764201600000, 90515.94357835098],
  [1764288000000, 91323.62827620257],
  [1764374400000, 90904.86767344688],
  [1764460800000, 90832.18685385384],
  [1764547200000, 90359.86873169734],
  [1764633600000, 86303.89766361401],
  [1764720000000, 91320.07942505728],
  [1764806400000, 93428.59451478458],
  [1764892800000, 92119.19047831658],
  [1764979200000, 89264.22915485654],
  [1765065600000, 89227.45274823112],
  [1765152000000, 90398.44875659447],
  [1765238400000, 90626.0373431212],
  [1765324800000, 92686.10402025311],
  [1765411200000, 91986.58107213798],
  [1765497600000, 92525.8680026296],
  [1765584000000, 90260.54242242372],
  [1765670400000, 90253.11813342397],
  [1765756800000, 88184.41093067056],
  [1765843200000, 86413.22138097929],
  [1765929600000, 87719.68139798648],
  [1766016000000, 86196.82137334664],
  [1766102400000, 85450.17964790671],
  [1766188800000, 88091.69571216944],
  [1766275200000, 88348.27802016199],
  [1766361600000, 88672.32967904503],
  [1766448000000, 88489.72404150236],
  [1766534400000, 87496.14669239183],
  [1766620800000, 87589.01664996856],
  [1766707200000, 87192.23473670239],
  [1766793600000, 87303.04428036696],
  [1766880000000, 87852.98655230374],
  [1766966400000, 87867.03943448896],
  [1767052800000, 87154.68240604762],
  [1767139200000, 88363.72223633934],
  [1767225600000, 87575.04615968224],
  [1767312000000, 88764.12624075128],
  [1767398400000, 89978.91920361611],
  [1767484800000, 90614.40684381907],
  [1767571200000, 91879.5772256957],
  [1767657600000, 93879.9479734475],
  [1767744000000, 93649.6319764084],
  [1767830400000, 91286.03314397692],
  [1767916800000, 91027.66616983686],
  [1768003200000, 90551.71363174269],
  [1768089600000, 90420.29795170767],
  [1768176000000, 90856.55910152226],
  [1768262400000, 91200.62761511702],
  [1768348800000, 95429.1573224277],
  [1768435200000, 96898.76071081961],
  [1768521600000, 95593.30783680787],
  [1768608000000, 95523.1861982478],
  [1768694400000, 94802.88170431636],
  [1768780800000, 93344.2194849136],
  [1768867200000, 92566.01277952259],
  [1768953600000, 88416.88686186896],
  [1769040000000, 89453.90473719541],
  [1769126400000, 89483.65163014928],
  [1769212800000, 89524.84864062016],
  [1769299200000, 89149.95970929884],
  [1769385600000, 86625.33128140382],
  [1769472000000, 88249.90141827049],
  [1769558400000, 89141.65035979386],
  [1769644800000, 89212.20824183176],
  [1769731200000, 84630.42066738439],
  [1769817600000, 84091.63017682909],
  [1769904000000, 78647.02739790398],
  [1769990400000, 76895.58665593083],
  [1770076800000, 78670.58922752787],
  [1770163200000, 75628.04173330522],
  [1770249600000, 73059.17986713687],
  [1770336000000, 62778.217566354324],
  [1770422400000, 70272.52223140873],
  [1770508800000, 69245.78200906444],
  [1770595200000, 70398.0850329669],
  [1770681600000, 70175.14749173766],
  [1770768000000, 68841.8723764457],
  [1770854400000, 67090.5793396472],
  [1770940800000, 66258.52954947444],
  [1771027200000, 68837.58112429692],
  [1771113600000, 69799.5509626349],
  [1771200000000, 68778.84298479716],
  [1771286400000, 68859.77618747062],
  [1771372800000, 67559.29573331702],
  [1771459200000, 66426.61953458567],
  [1771545600000, 66976.02936410521],
  [1771632000000, 68002.9401106256],
  [1771718400000, 68026.03124326779],
  [1771804800000, 65192.18870120006],
  [1771891200000, 64737.90196985264],
  [1771977600000, 64073.54894566756],
  [1772064000000, 67850.10521282951],
  [1772150400000, 67496.84163950248],
  [1772236800000, 65891.22197698704],
  [1772323200000, 67017.07604771722],
  [1772409600000, 65824.42166938317],
  [1772496000000, 68815.9363388441],
  [1772582400000, 68287.46303403362],
  [1772668800000, 72752.30156666112],
  [1772755200000, 70868.21819643723],
  [1772841600000, 68142.88312387785],
  [1772928000000, 67339.67440056572],
  [1773014400000, 66042.7510790264],
  [1773100800000, 68430.60926017091],
  [1773187200000, 69849.2035305081],
  [1773273600000, 70028.95987601393],
  [1773360000000, 70417.19388567522],
  [1773446400000, 70838.93230193328],
  [1773532800000, 71149.2823885419],
  [1773619200000, 72934.2940718683],
  [1773705600000, 74679.37090810013],
  [1773792000000, 74004.69080880683],
  [1773878400000, 71220.04730260483],
  [1773964800000, 69936.19932093748],
  [1774051200000, 70526.28915957874],
  [1774137600000, 68424.07687771624],
  [1774224000000, 67933.42948137881],
  [1774310400000, 70987.25185405998],
  [1774396800000, 70528.86345595501],
  [1774483200000, 71303.58545062262],
  [1774569600000, 68727.2122901201],
  [1774656000000, 66329.88185741157],
  [1774742400000, 66388.84446013413],
  [1774828800000, 65947.03192607871],
  [1774915200000, 66691.27147786925],
  [1775001600000, 68107.47456405059],
  [1775088000000, 67959.87524726024],
  [1775174400000, 66887.51063938277],
  [1775260800000, 66822.55230312092],
  [1775347200000, 67077.1500532805],
  [1775433600000, 69002.03847938096],
  [1775520000000, 68672.24657456316],
  [1775606400000, 71661.76372427847],
  [1775692800000, 70644.79416156793],
  [1775779200000, 71367.80291658688],
  [1775865600000, 72920.25491187068],
  [1775952000000, 73021.85968305328],
  [1776038400000, 70660.63961180339],
  [1776124800000, 74481.64142860245],
  [1776211200000, 74297.34759499803],
  [1776297600000, 74826.31308825641],
  [1776384000000, 75111.95674547968],
  [1776470400000, 77125.73357198425],
  [1776556800000, 75716.15083727139],
  [1776643200000, 73841.02173808741],
  [1776729600000, 75858.03546790924],
  [1776816000000, 76326.19170242558],
  [1776902400000, 78238.81675008619],
  [1776988800000, 78275.32582745969],
  [1777075200000, 77447.61757991764],
  [1777161600000, 77634.51592192693],
  [1777248000000, 78637.74356150378],
  [1777334400000, 77366.78442217235],
  [1777420800000, 76331.86443470464],
  [1777507200000, 75784.95743624517],
  [1777593600000, 76296.7964844269],
  [1777680000000, 78207.76425489692],
  [1777766400000, 78677.4246327222],
  [1777852800000, 78512.09246456268],
  [1777939200000, 79825.8751129579],
  [1778025600000, 80913.9613749304],
  [1778112000000, 81436.85936825167],
  [1778198400000, 80024.90767231231],
  [1778284800000, 80197.2669977041],
  [1778371200000, 80677.64981723971],
  [1778457600000, 82018.3711243874],
  [1778544000000, 81627.56604995472],
  [1778630400000, 80482.14377829393],
  [1778716800000, 79288.8420865621],
  [1778803200000, 81059.11595417073],
  [1778889600000, 79068.6684041429],
  [1778976000000, 78132.7535126921],
  [1779062400000, 77428.51866052429],
  [1779148800000, 76959.40571528324],
  [1779235200000, 76758.73155866472],
  [1779321600000, 77470.39614899461],
  [1779408000000, 77550.38308320483],
  [1779494400000, 75478.38285862996],
  [1779580800000, 76684.37097078416],
  [1779667200000, 77016.06581859986],
  [1779753600000, 77258.39912360838],
  [1779840000000, 75851.10409561773],
  [1779926400000, 74339.61694703094],
  [1780012800000, 73651.64255141478],
  [1780099200000, 73500.91507629369],
  [1780185600000, 73820.30385315015],
  [1780272000000, 73598.6681238158],
  [1780358400000, 71320.29306465392],
  [1780444800000, 66727.26415497709],
  [1780531200000, 64046.61064609333],
  [1780617600000, 63810.65923840883],
  [1780704000000, 60960.10140035313],
  [1780790400000, 60855.25426528331],
  [1780876800000, 63273.537430635515],
  [1780963200000, 63069.147792658114],
  [1781049600000, 61669.76384194788],
  [1781136000000, 61480.144432833426],
  [1781222400000, 63555.66181107698],
  [1781308800000, 63532.27782485316],
  [1781395200000, 64408.80975375945],
  [1781481600000, 65709.31094599118],
  [1781568000000, 66292.50117921834],
  [1781654400000, 65619.28080038042],
  [1781740800000, 64444.545329668814],
  [1781827200000, 62897.23855524796],
  [1781913600000, 63489.81094752525],
  [1782000000000, 64253.39869532133],
  [1782086400000, 63255.48525259375],
  [1782172800000, 63937.28526422244],
  [1782259200000, 62662.29201921944],
  [1782345600000, 60989.57352152134],
  [1782432000000, 59726.73653480851],
  [1782518400000, 60022.32566638378],
  [1782604800000, 59953.443344011124],
  [1782691200000, 59494.606386317784],
  [1782777600000, 60152.35872063589],
  [1782864000000, 58566.091991843154],
  [1782950400000, 59967.685041718134],
  [1783036800000, 61490.21448471664],
  [1783123200000, 62553.61289177051],
  [1783209600000, 63088.406753852214],
  [1783296000000, 63586.102141021256],
  [1783382400000, 64001.23542391328],
  [1783468800000, 63335.30929080668],
  [1783555200000, 62247.1304822092],
  [1783641600000, 63192.8789720319],
  [1783728000000, 64110.97482196822],
  [1783814400000, 63791.35305345348],
  [1783900800000, 63746.65595793199],
  [1783987200000, 62278.96301585648],
  [1784073600000, 64983.51907427709],
  [1784160000000, 64717.168891130066],
  [1784246400000, 63792.28742743447],
  [1784332800000, 63904.954014943025],
  [1784419200000, 64795.70382303786],
  [1784505600000, 64670.40117470696],
  [1784592000000, 65184.92144270268],
  [1784678400000, 66520.98164575922],
  [1784764800000, 66077.05646514206],
  [1784851200000, 65052.47667067735],
  [1784937600000, 64092.64739795451],
  [1785024000000, 64318.24520120312],
  [1785110400000, 65343.824510845894],
  [1785196800000, 63701.35288114535],
  [1785283200000, 63881.94327943538],
  [1785369600000, 63916.59794922001],
  [1785456000000, 64743.33714554026],
  [1785542400000, 62820.08613814001],
  [1785628800000, 62772.57726413174],
  [1785715200000, 63504.41559755184],
  [1785801600000, 63465.19968911304],
  [1785888000000, 64062.173729779366],
  [1785974400000, 64608.705388357404],
  [1786060800000, 64262.74830979173],
  [1786147200000, 64879.7560855934],
  [1786233600000, 64917.23929330571],
  [1786320000000, 64856.097825382276],
  [1786406400000, 63915.71213556821],
  [1786492800000, 63537.55988964766],
  [1786579200000, 63408.625697113624],
  [1786665600000, 63429.17906286841],
  [1786752000000, 62984.28959582886],
  [1786838400000, 63031.04825975698],
  [1786924800000, 62843.70368466329],
  [1787011200000, 64491.345282946255],
  [1787097600000, 64686.25782561655],
  [1787184000000, 69291.0104297816],
  [1787270400000, 73020.94563440893],
  [1787356800000, 78317.77716345884],
  [1787443200000, 77081.02299000922],
  [1787529600000, 77712.3200924702],
  [1787616000000, 78973.88693602335],
  [1787702400000, 78511.2331116067],
  [1787788800000, 79018.03405750773],
  [1787875200000, 80268.37474707834],
  [1787961600000, 77820.76428719184],
  [1788048000000, 78225.13950818499],
  [1788134400000, 77658.23133225394],
  [1788220800000, 78552.77932895812],
  [1788307200000, 77416.44110979848],
  [1788393600000, 77297.13347191992],
  [1788480000000, 81264.70153038795],
  [1788566400000, 79671.25767420157],
  [1788652800000, 79821.69873179746],
  [1788739200000, 80329.3478460037],
  [1788825600000, 79093.4641898418],
  [1788912000000, 78450.75303870205],
  [1788998400000, 78283.06047169256],
  [1789084800000, 76554.98664973286],
  [1789171200000, 77203.53444805603],
  [1789257600000, 77261.62722069985],
  [1789344000000, 76819.04496746542],
  [1789430400000, 78173.35158344489],
  [1789516800000, 75590.24471973324],
  [1789603200000, 76146.81236783884],
  [1789689600000, 76371.3617203135],
  [1789776000000, 80873.58287659245],
  [1789862400000, 81236.41383660372],
  [1789948800000, 81169.03511950027],
  [1790035200000, 86596.74004249526],
  [1790121600000, 86183.29442787907],
  [1790208000000, 84382.39990356649],
  [1790294400000, 84377.96508359577],
  [1790380800000, 84075.71659039952],
  [1790467200000, 84416.7149816521],
  [1790553600000, 84448.75015162026],
  [1790640000000, 83479.2543356063],
  [1790726400000, 83640.10160067653],
  [1790812800000, 83576.13460018387],
  [1790899200000, 84841.66634358242],
  [1790985600000, 84506.46895963937],
  [1791041660000, 84780.0524284486]],
 'market_caps': [[1759536000000, 2437130562668.8506],
  [1759622400000, 2438832157552.7866],
  [1759708800000, 2461262484402.037],
  [1759795200000, 2486786743153.339],
  [1759881600000, 2419756015403.5737],
  [1759968000000, 2458603013498.3677],
  [1760054400000, 2425643508379.291],
  [1760140800000, 2255299161767.251],
  [1760227200000, 2208268263699.5435],
  [1760313600000, 2296145057231.311],
  [1760400000000, 2297230038136.1206],
  [1760486400000, 2255593612790.7695],
  [1760572800000, 2207806038542.883],
  [1760659200000, 2154964541836.455],
  [1760745600000, 2122018970045.2217],
  [1760832000000, 2137453218003.543],
  [1760918400000, 2165876768810.395],
  [1761004800000, 2204762231502.6216],
  [1761091200000, 2160928131234.672],
  [1761177600000, 2146123605489.606],
  [1761264000000, 2194925940893.7788],
  [1761350400000, 2213139524569.58],
  [1761436800000, 2226000980105.0205],
  [1761523200000, 2282298627073.1055],
  [1761609600000, 2275880103405.9155],
  [1761696000000, 2252121103480.7026],
  [1761782400000, 2195202860989.228],
  [1761868800000, 2159719137272.1077],
  [1761955200000, 2184958376796.8809],
  [1762041600000, 2194472770726.0208],
  [1762128000000, 2206951286346.512],
  [1762214400000, 2125234946159.2783],
  [1762300800000, 2027117373395.1697],
  [1762387200000, 2072420580091.9111],
  [1762473600000, 2019505617727.349],
  [1762560000000, 2061483488853.8977],
  [1762646400000, 2040163403275.169],
  [1762732800000, 2088246864454.0945],
  [1762819200000, 2113691346622.1785],
  [1762905600000, 2055081880355.954],
  [1762992000000, 2025171098463.4424],
  [1763078400000, 1989587716654.155],
  [1763164800000, 1883528419611.1135],
  [1763251200000, 1906286799108.28],
  [1763337600000, 1879821625636.488],
  [1763424000000, 1836812997467.337],
  [1763510400000, 1852965766035.4404],
  [1763596800000, 1824001855237.545],
  [1763683200000, 1730169291917.76],
  [1763769600000, 1696834479574.6868],
  [1763856000000, 1689663589864.315],
  [1763942400000, 1731240703090.288],
  [1764028800000, 1760876158638.0408],
  [1764115200000, 1742579106347.7073],
  [1764201600000, 1805319494740.8276],
  [1764288000000, 1821686350208.8733],
  [1764374400000, 1814035459752.682],
  [1764460800000, 1812771321410.944],
  [1764547200000, 1804580223118.8345],
  [1764633600000, 1722165915578.808],
  [1764720000000, 1823014041001.2756],
  [1764806400000, 1867918440559.5425],
  [1764892800000, 1838202452874.2395],
  [1764979200000, 1783420367861.1216],
  [1765065600000, 1781473275096.9917],
  [1765152000000, 1802958541728.722],
  [1765238400000, 1808501444019.7495],
  [1765324800000, 1850293655502.181],
  [1765411200000, 1837368941062.516],
  [1765497600000, 1847119089483.3413],
  [1765584000000, 1801893841647.4097],
  [1765670400000, 1802028910320.9023],
  [1765756800000, 1760354230589.3552],
  [1765843200000, 1725206666830.8127],
  [1765929600000, 1753485223429.683],
  [1766016000000, 1718910200047.374],
  [1766102400000, 1705923883033.444],
  [1766188800000, 1758617508011.9905],
  [1766275200000, 1763949555471.3745],
  [1766361600000, 1769182018548.0688],
  [1766448000000, 1767230408064.2593],
  [1766534400000, 1745170281695.8684],
  [1766620800000, 1749380269942.6577],
  [1766707200000, 1741524937162.2537],
  [1766793600000, 1743265213477.923],
  [1766880000000, 1753170406449.7837],
  [1766966400000, 1753776420254.8835],
  [1767052800000, 1740448227093.1155],
  [1767139200000, 1765901370591.8586],
  [1767225600000, 1748854230148.607],
  [1767312000000, 1772643389813.6357],
  [1767398400000, 1796943351423.4443],
  [1767484800000, 1809678441959.2795],
  [1767571200000, 1834987309777.0288],
  [1767657600000, 1874977643561.6355],
  [1767744000000, 1870414277860.5935],
  [1767830400000, 1823249641248.364],
  [1767916800000, 1818127709176.3096],
  [1768003200000, 1808660912220.566],
  [1768089600000, 1806081524434.709],
  [1768176000000, 1814830239671.1992],
  [1768262400000, 1821743571887.9038],
  [1768348800000, 1906249903552.0205],
  [1768435200000, 1935642376552.2793],
  [1768521600000, 1909607764838.513],
  [1768608000000, 1908245771104.619],
  [1768694400000, 1893940780540.7515],
  [1768780800000, 1864801600128.905],
  [1768867200000, 1849293615306.6567],
  [1768953600000, 1766441725515.5132],
  [1769040000000, 1787198131481.9512],
  [1769126400000, 1787836917555.1865],
  [1769212800000, 1788698866227.4563],
  [1769299200000, 1781238125881.8794],
  [1769385600000, 1730823322190.6162],
  [1769472000000, 1763317661992.5044],
  [1769558400000, 1781169624000.1633],
  [1769644800000, 1782608191361.8965],
  [1769731200000, 1691092174731.011],
  [1769817600000, 1680358897717.733],
  [1769904000000, 1571576493914.8904],
  [1769990400000, 1536578056063.6562],
  [1770076800000, 1572047321850.9954],
  [1770163200000, 1511249141910.282],
  [1770249600000, 1460053444889.3728],
  [1770336000000, 1254617718584.4033],
  [1770422400000, 1404422427900.4514],
  [1770508800000, 1383938789934.4868],
  [1770595200000, 1407004286702.8896],
  [1770681600000, 1402584286978.939],
  [1770768000000, 1376158047090.4307],
  [1770854400000, 1340996637525.7053],
  [1770940800000, 1324400733134.6533],
  [1771027200000, 1375985529045.6062],
  [1771113600000, 1395251772208.4526],
  [1771200000000, 1374891409746.7566],
  [1771286400000, 1376546726938.174],
  [1771372800000, 1350583353307.6948],
  [1771459200000, 1327971882876.0806],
  [1771545600000, 1338989802249.3938],
  [1771632000000, 1359548508149.9219],
  [1771718400000, 1360035939392.7476],
  [1771804800000, 1303412071350.4219],
  [1771891200000, 1294359253920.9185],
  [1771977600000, 1281109347803.1018],
  [1772064000000, 1356652404814.3232],
  [1772150400000, 1349617910213.303],
  [1772236800000, 1317542293327.2354],
  [1772323200000, 1340085381689.69],
  [1772409600000, 1316266670911.0593],
  [1772496000000, 1376116545555.9185],
  [1772582400000, 1365575947099.492],
  [1772668800000, 1454892523976.9167],
  [1772755200000, 1417251399988.9395],
  [1772841600000, 1362780115876.562],
  [1772928000000, 1346745070785.4204],

In [41]:
df_btc = pd.DataFrame(data['prices'], columns=['timestamp', 'price_usd'])
df_btc['date'] = pd.to_datetime(df_btc['timestamp'], unit='ms')
df_btc

         timestamp      price_usd                date
0    1759536000000  122294.924417 2025-10-04 00:00:00
1    1759622400000  122428.890634 2025-10-05 00:00:00
2    1759708800000  123488.730597 2025-10-06 00:00:00
3    1759795200000  124739.810888 2025-10-07 00:00:00
4    1759881600000  121463.118082 2025-10-08 00:00:00
..             ...            ...                 ...
361  1790726400000   83640.101601 2026-09-30 00:00:00
362  1790812800000   83576.134600 2026-10-01 00:00:00
363  1790899200000   84841.666344 2026-10-02 00:00:00
364  1790985600000   84506.468960 2026-10-03 00:00:00
365  1791041660000   84780.052428 2026-10-03 15:34:20

[366 rows x 3 columns]

## Istat

In [78]:
import requests
import time
from io import StringIO

In [ ]:
#esploriamo constraints del dataset

url =   "https://esploradati.istat.it/SDMXWS/rest/availableconstraint/41_983/all/all?mode=available"
#headers = {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}

while True:
    response_constraints = requests.get(url, verify=False)

    if response_constraints.status_code == 200:
        print("Richiesta riuscita!")
        break

    print(f"Status code: {response_constraints.status_code}. Riprovo tra 15 secondi...")
    time.sleep(15)

### Dati incidenti

In [114]:
# schema URL https://esploradati.istat.it/SDMXWS/rest/data/flowRef/dim1.dim2.dim3.dim4.dim5/
# schema URL https://esploradati.istat.it/SDMXWS/rest/data/flowRef/.........?startPeriod=2016&endPeriod=2


url =   "https://esploradati.istat.it/SDMXWS/rest/data/41_983?startPeriod=2001&endPeriod=2024"
headers = {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}

while True:
    response_incidenti = requests.get(url, headers=headers, verify=False)

    if response_incidenti.status_code == 200:
        print("Richiesta riuscita!")
        break

    print(f"Status code: {response_incidenti.status_code}. Riprovo tra 15 secondi...")
    time.sleep(15)

Richiesta riuscita!

In [117]:
#converto la stringa response.text come se fosse un file CSV. Poi Panda la converte in un df.
df_incidenti = pd.read_csv(StringIO(response_incidenti.text))

In [118]:
df_incidenti

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
0,IT1:41_983(1.0),A,1001,KILLINJ,F,2001,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT1:41_983(1.0),A,1001,KILLINJ,F,2002,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT1:41_983(1.0),A,1001,KILLINJ,F,2003,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IT1:41_983(1.0),A,1001,KILLINJ,F,2004,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IT1:41_983(1.0),A,1001,KILLINJ,F,2005,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573547,IT1:41_983(1.0),A,111107,ROADACC,9,2020,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573548,IT1:41_983(1.0),A,111107,ROADACC,9,2021,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573549,IT1:41_983(1.0),A,111107,ROADACC,9,2022,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573550,IT1:41_983(1.0),A,111107,ROADACC,9,2023,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573551,IT1:41_983(1.0),A,111107,ROADACC,9,2024,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Dati sui comuni: nome, superficie

In [120]:
url_comuni_dimensioni = 'https://situas-servizi.istat.it/publish/reportspooljson?pfun=74&pdata=31/12/2020'
response_comuniNomeSuperficie = requests.get(url_comuni_dimensioni, verify=False)

In [123]:
response_comuniNomeSuperficie.json()['resultset']

[{'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001001',
  'PRO_COM': 1001,
  'COMUNE': 'Agliè',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 2644,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 13.1462,
  'ANNO_AREA': '2020',
  'POP_RES': 2545,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001002',
  'PRO_COM': 1002,
  'COMUNE': 'Airasca',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3819,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 15.7393,
  'ANNO_AREA': '2020',
  'POP_RES': 3633,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001003',
  'PRO_COM': 1003,
  'COMUNE': 'Ala di Stura',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 462,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 46.3315,
  'ANNO_AREA': '2020',
  'POP_RES': 459,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001004',
  'PRO_COM': 1004,
  'COMUNE': "Albiano d'Ivrea",
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1791,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.7314,
  'ANNO_AREA': '2020',
  'POP_RES': 1638,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001006',
  'PRO_COM': 1006,
  'COMUNE': 'Almese',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 6303,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 17.8756,
  'ANNO_AREA': '2020',
  'POP_RES': 6355,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001007',
  'PRO_COM': 1007,
  'COMUNE': 'Alpette',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 277,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 5.6261,
  'ANNO_AREA': '2020',
  'POP_RES': 235,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001008',
  'PRO_COM': 1008,
  'COMUNE': 'Alpignano',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 16893,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.9193,
  'ANNO_AREA': '2020',
  'POP_RES': 16484,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001009',
  'PRO_COM': 1009,
  'COMUNE': 'Andezeno',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1966,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 7.486,
  'ANNO_AREA': '2020',
  'POP_RES': 2013,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001010',
  'PRO_COM': 1010,
  'COMUNE': 'Andrate',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 512,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 9.3085,
  'ANNO_AREA': '2020',
  'POP_RES': 488,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001011',
  'PRO_COM': 1011,
  'COMUNE': 'Angrogna',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 870,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 38.8782,
  'ANNO_AREA': '2020',
  'POP_RES': 838,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001012',
  'PRO_COM': 1012,
  'COMUNE': 'Arignano',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1039,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 8.1668,
  'ANNO_AREA': '2020',
  'POP_RES': 1080,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001013',
  'PRO_COM': 1013,
  'COMUNE': 'Avigliana',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 12129,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 23.2172,
  'ANNO_AREA': '2020',
  'POP_RES': 12351,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001014',
  'PRO_COM': 1014,
  'COMUNE': 'Azeglio',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1347,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 9.9605,
  'ANNO_AREA': '2020',
  'POP_RES': 1235,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001015',
  'PRO_COM': 1015,
  'COMUNE': 'Bairo',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 816,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 7.0859,
  'ANNO_AREA': '2020',
  'POP_RES': 787,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001016',
  'PRO_COM': 1016,
  'COMUNE': 'Balangero',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3161,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 13.0063,
  'ANNO_AREA': '2020',
  'POP_RES': 3064,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001017',
  'PRO_COM': 1017,
  'COMUNE': 'Baldissero Canavese',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 534,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 4.5064,
  'ANNO_AREA': '2020',
  'POP_RES': 533,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001018',
  'PRO_COM': 1018,
  'COMUNE': 'Baldissero Torinese',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3783,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 15.4054,
  'ANNO_AREA': '2020',
  'POP_RES': 3671,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001019',
  'PRO_COM': 1019,
  'COMUNE': 'Balme',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 95,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 62.7105,
  'ANNO_AREA': '2020',
  'POP_RES': 110,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001020',
  'PRO_COM': 1020,
  'COMUNE': 'Banchette',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3280,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 2.0289,
  'ANNO_AREA': '2020',
  'POP_RES': 3112,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001021',
  'PRO_COM': 1021,
  'COMUNE': 'Barbania',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1623,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 12.8027,
  'ANNO_AREA': '2020',
  'POP_RES': 1585,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001022',
  'PRO_COM': 1022,
  'COMUNE': 'Bardonecchia',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3212,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 132.203,
  'ANNO_AREA': '2020',
  'POP_RES': 3078,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001023',
  'PRO_COM': 1023,
  'COMUNE': 'Barone Canavese',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 599,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 3.9864,
  'ANNO_AREA': '2020',
  'POP_RES': 559,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001024',
  'PRO_COM': 1024,
  'COMUNE': 'Beinasco',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 18104,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 6.7343,
  'ANNO_AREA': '2020',
  'POP_RES': 17532,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001025',
  'PRO_COM': 1025,
  'COMUNE': 'Bibiana',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3376,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 18.5979,
  'ANNO_AREA': '2020',
  'POP_RES': 3392,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001026',
  'PRO_COM': 1026,
  'COMUNE': 'Bobbio Pellice',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 566,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 94.0819,
  'ANNO_AREA': '2020',
  'POP_RES': 537,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001027',
  'PRO_COM': 1027,
  'COMUNE': 'Bollengo',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 2112,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 14.2234,
  'ANNO_AREA': '2020',
  'POP_RES': 2097,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001028',
  'PRO_COM': 1028,
  'COMUNE': 'Borgaro Torinese',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 11723,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.1039,
  'ANNO_AREA': '2020',
  'POP_RES': 11773,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001029',
  'PRO_COM': 1029,
  'COMUNE': 'Borgiallo',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 550,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 6.9648,
  'ANNO_AREA': '2020',
  'POP_RES': 592,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001030',
  'PRO_COM': 1030,
  'COMUNE': "Borgofranco d'Ivrea",
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3643,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 13.4189,
  'ANNO_AREA': '2020',
  'POP_RES': 3590,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001031',
  'PRO_COM': 1031,
  'COMUNE': 'Borgomasino',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 835,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 12.3712,
  'ANNO_AREA': '2020',
  'POP_RES': 772,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001032',
  'PRO_COM': 1032,
  'COMUNE': 'Borgone Susa',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 2320,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 4.9617,
  'ANNO_AREA': '2020',
  'POP_RES': 2187,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001033',
  'PRO_COM': 1033,
  'COMUNE': 'Bosconero',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3056,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 10.919,
  'ANNO_AREA': '2020',
  'POP_RES': 3074,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001034',
  'PRO_COM': 1034,
  'COMUNE': 'Brandizzo',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 8402,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 6.2914,
  'ANNO_AREA': '2020',
  'POP_RES': 8798,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001035',
  'PRO_COM': 1035,
  'COMUNE': 'Bricherasio',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 4517,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 22.7585,
  'ANNO_AREA': '2020',
  'POP_RES': 4564,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001036',
  'PRO_COM': 1036,
  'COMUNE': 'Brosso',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 460,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.135,
  'ANNO_AREA': '2020',
  'POP_RES': 402,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001037',
  'PRO_COM': 1037,
  'COMUNE': 'Brozolo',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 471,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 8.9504,
  'ANNO_AREA': '2020',
  'POP_RES': 449,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001038',
  'PRO_COM': 1038,
  'COMUNE': 'Bruino',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 8479,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 5.5701,
  'ANNO_AREA': '2020',
  'POP_RES': 8475,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001039',
  'PRO_COM': 1039,
  'COMUNE': 'Brusasco',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1726,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 14.3592,
  'ANNO_AREA': '2020',
  'POP_RES': 1482,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001040',
  'PRO_COM': 1040,
  'COMUNE': 'Bruzolo',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1545,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 12.5598,
  'ANNO_AREA': '2020',
  'POP_RES': 1487,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001041',
  'PRO_COM': 1041,
  'COMUNE': 'Buriasco',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1405,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 14.6868,
  'ANNO_AREA': '2020',
  'POP_RES': 1329,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001042',
  'PRO_COM': 1042,
  'COMUNE': 'Burolo',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1228,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 5.476,
  'ANNO_AREA': '2020',
  'POP_RES': 1134,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001043',
  'PRO_COM': 1043,
  'COMUNE': 'Busano',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1588,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 5.0591,
  'ANNO_AREA': '2020',
  'POP_RES': 1622,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001044',
  'PRO_COM': 1044,
  'COMUNE': 'Bussoleno',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 6363,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 37.0661,
  'ANNO_AREA': '2020',
  'POP_RES': 5703,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001045',
  'PRO_COM': 1045,
  'COMUNE': 'Buttigliera Alta',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 6386,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 8.0973,
  'ANNO_AREA': '2020',
  'POP_RES': 6292,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001046',
  'PRO_COM': 1046,
  'COMUNE': 'Cafasse',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 3511,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 10.2312,
  'ANNO_AREA': '2020',
  'POP_RES': 3334,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001047',
  'PRO_COM': 1047,
  'COMUNE': 'Caluso',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 7483,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 39.4925,
  'ANNO_AREA': '2020',
  'POP_RES': 7344,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001048',
  'PRO_COM': 1048,
  'COMUNE': 'Cambiano',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 6215,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 14.1314,
  'ANNO_AREA': '2020',
  'POP_RES': 5915,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001049',
  'PRO_COM': 1049,
  'COMUNE': 'Campiglione Fenile',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1382,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.0863,
  'ANNO_AREA': '2020',
  'POP_RES': 1333,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001050',
  'PRO_COM': 1050,
  'COMUNE': 'Candia Canavese',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 1286,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 9.1318,
  'ANNO_AREA': '2020',
  'POP_RES': 1219,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001051',
  'PRO_COM': 1051,
  'COMUNE': 'Candiolo',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 5566,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.8499,
  'ANNO_AREA': '2020',
  'POP_RES': 5627,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001052',
  'PRO_COM': 1052,
  'COMUNE': 'Canischio',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 294,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.9505,
  'ANNO_AREA': '2020',
  'POP_RES': 277,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001053',
  'PRO_COM': 1053,
  'COMUNE': 'Cantalupa',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 2527,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.1953,
  'ANNO_AREA': '2020',
  'POP_RES': 2574,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001054',
  'PRO_COM': 1054,
  'COMUNE': 'Cantoira',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 554,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 23.0319,
  'ANNO_AREA': '2020',
  'POP_RES': 588,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001055',
  'PRO_COM': 1055,
  'COMUNE': 'Caprie',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 2116,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 16.4078,
  'ANNO_AREA': '2020',
  'POP_RES': 2057,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001056',
  'PRO_COM': 1056,
  'COMUNE': 'Caravino',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 995,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 11.5371,
  'ANNO_AREA': '2020',
  'POP_RES': 901,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',
  'PRO_COM_T': '001057',
  'PRO_COM': 1057,
  'COMUNE': 'Carema',
  'SIGLA_AUTOMOBILISTICA': 'TO',
  'CC_UTS': 0,
  'CC_REG': 0,
  'POP_LEG': 772,
  'ANNO_CENSIMENTO': '2011',
  'AREA_KMQ': 10.2579,
  'ANNO_AREA': '2020',
  'POP_RES': 739,
  'ANNO_POP_RES': '2020'},
 {'COD_RIP': 1,
  'COD_REG': '01',
  'COD_PROV_STORICO': '001',
  'COD_UTS': '201',

In [124]:
df_comuniNomeSuperficie = pd.DataFrame.from_dict(response_comuniNomeSuperficie.json()['resultset'])

In [125]:
df_comuniNomeSuperficie

,COD_RIP,COD_REG,COD_PROV_STORICO,COD_UTS,PRO_COM_T,PRO_COM,COMUNE,SIGLA_AUTOMOBILISTICA,CC_UTS,CC_REG,POP_LEG,ANNO_CENSIMENTO,AREA_KMQ,ANNO_AREA,POP_RES,ANNO_POP_RES,COMUNE_A
0,1,01,001,201,001001,1001,Agliè,TO,0,0,2644,2011,13.1462,2020,2545,2020,NaN
1,1,01,001,201,001002,1002,Airasca,TO,0,0,3819,2011,15.7393,2020,3633,2020,NaN
2,1,01,001,201,001003,1003,Ala di Stura,TO,0,0,462,2011,46.3315,2020,459,2020,NaN
3,1,01,001,201,001004,1004,Albiano d'Ivrea,TO,0,0,1791,2011,11.7314,2020,1638,2020,NaN
4,1,01,001,201,001006,1006,Almese,TO,0,0,6303,2011,17.8756,2020,6355,2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7898,5,20,111,111,111103,111103,Villaputzu,SU,0,0,4836,2011,181.3074,2020,4497,2020,NaN
7899,5,20,111,111,111104,111104,Villasalto,SU,0,0,1127,2011,130.3596,2020,999,2020,NaN
7900,5,20,111,111,111105,111105,Villasimius,SU,0,0,3420,2011,57.9708,2020,3688,2020,NaN
7901,5,20,111,111,111106,111106,Villasor,SU,0,0,6857,2011,86.7935,2020,6636,2020,NaN
7902,5,20,111,111,111107,111107,Villaspeciosa,SU,0,0,2407,2011,27.1937,2020,2549,2020,NaN

### Dati comuni popolazione
source dati 2001-2018: https://demo.istat.it/app/?i=RBD&l=it

souce dati 2019-2025: https://demo.istat.it/app/?l=it&a=2025&i=P02