In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import seaborn as sns
import statsmodels as sm
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [2]:
df = pd.read_csv('data/comuni_dashboard_df.csv')

df

,Codice Comune,Nome,Trend Incidenti,p-value,Incidentix1000abitanti,Incidentixkm²,Gravità Incidenti,Ampiezza demografica - Theme,Ampiezza demografica - SubTheme
0,1001,Agliè,-0.053404,0.048158,1.53,0.31,1.66,<10k,2k-3k
1,1002,Airasca,-0.187463,0.000016,3.08,0.72,1.61,<10k,3k-5k
2,1003,Ala di Stura,0.050023,0.100870,0.50,0.00,1.60,<10k,< 500
3,1004,Albiano d'Ivrea,-0.086664,0.051387,2.68,0.39,1.67,<10k,1k-2k
4,1005,Alice Superiore,-0.089647,0.187080,1.72,0.16,1.83,<10k,500-999
...,...,...,...,...,...,...,...,...,...
8569,111103,Villaputzu,-0.009250,0.940114,1.46,0.04,1.64,<10k,3k-5k
8570,111104,Villasalto,-0.099536,0.790368,2.35,0.02,1.42,<10k,1k-2k
8571,111105,Villasimius,0.086857,0.482700,1.62,0.10,1.37,<10k,3k-5k
8572,111106,Villasor,-0.094643,0.230676,2.03,0.16,1.65,<10k,5k-10k
8573,111107,Villaspeciosa,-0.080714,0.666559,1.54,0.15,1.37,<10k,2k-3k

In [5]:
df.describe()

,Codice Comune,Trend Incidenti,p-value,Incidentix1000abitanti,Incidentixkm²,Gravità Incidenti
count,8574.000000,8574.000000,8.495000e+03,8574.000000,8574.000000,8497.000000
mean,46050.965594,-0.042153,2.766942e-01,1.992321,0.730145,1.550535
std,33080.916115,0.123640,3.033438e-01,1.677603,2.043164,0.289352
min,1001.000000,-2.691765,1.336615e-15,0.000000,0.000000,1.000000
25%,16199.250000,-0.085246,1.233416e-02,0.850000,0.040000,1.380000
50%,41038.500000,-0.025364,1.451520e-01,1.600000,0.160000,1.510000
75%,75063.750000,0.014899,4.977894e-01,2.680000,0.570000,1.680000
max,111107.000000,1.548900,1.000000e+00,25.300000,65.030000,4.000000